import type { ResourceSchema } from '../core/models/schema.model';

/**
 * Colección reordenable — base.md §11, api.md §3.1.
 * `position` lo gestiona el backend (R3: nunca se expone como campo).
 */
export const categoriesSchema: ResourceSchema = {
  id: 'categories',
  label: 'Categoría',
  labelPlural: 'Categorías',
  kind: 'collection',
  endpoint: {
    list: '/admin/categories',
    get: '/admin/categories/{key}',
    create: '/admin/categories',
    update: '/admin/categories/{key}',
    remove: '/admin/categories/{key}',
  },
  keyField: 'slug',
  titleField: 'name',
  sortable: true,
  positionField: 'position',
  // Edición rápida del listado (plan 6.5): los dos campos que se repiten.
  quickEdit: ['name', 'active'],
  search: ['name'],
  filters: [{ key: 'active', label: 'Activo', type: 'boolean' }],
  listColumns: [
    { key: 'image_url', label: 'Imagen', format: 'thumbnail' },
    { key: 'name', label: 'Nombre' },
    { key: 'active', label: 'Activo', format: 'boolean' },
  ],
  layout: {
    mode: 'sections',
    sections: [
      { id: 'general', label: 'General' },
      { id: 'seo', label: 'SEO' },
      { id: 'contenido', label: 'Contenido' },
      { id: 'estado', label: 'Estado' },
    ],
  },
  fields: [
    {
      type: 'text',
      key: 'name',
      label: 'Nombre',
      required: true,
      section: 'general',
      width: 6,
    },
    {
      type: 'slug',
      key: 'slug',
      label: 'Slug',
      from: 'name',
      lockAfterCreate: true,
      required: true,
      validators: { unique: true },
      help: 'Se genera desde el nombre. Inmutable tras crear el registro.',
      section: 'general',
      width: 6,
    },
    {
      type: 'text',
      key: 'seo_title',
      label: 'Título SEO',
      required: true,
      help: 'Aparece en el resultado de buscadores.',
      section: 'seo',
      width: 12,
    },
    {
      type: 'textarea',
      key: 'seo_description',
      label: 'Descripción SEO',
      required: true,
      rows: 3,
      section: 'seo',
      width: 12,
    },
    {
      type: 'textarea',
      key: 'intro',
      label: 'Introducción',
      required: true,
      rows: 6,
      help: 'Texto de la categoría en la portada (100–1000 caracteres).',
      validators: { minLength: 100, maxLength: 1000 },
      section: 'contenido',
      width: 12,
    },
    {
      type: 'image',
      key: 'image_url',
      label: 'Imagen',
      required: true,
      section: 'contenido',
      width: 6,
    },
    {
      type: 'text',
      key: 'image_alt',
      label: 'Texto alternativo',
      help: 'Describe la imagen para lectores de pantalla.',
      section: 'contenido',
      width: 6,
    },
    {
      type: 'boolean',
      key: 'active',
      label: 'Activo',
      required: true,
      default: true,
      trueLabel: 'Activo',
      falseLabel: 'Inactivo',
      help: 'Si está inactivo, la categoría no sale en el sitio público.',
      section: 'estado',
      width: 6,
    },
  ],
};
