import type { ResourceSchema } from '../core/models/schema.model';

/**
 * Colección con pestañas — base.md §11, api.md §3.2–§3.5.
 * Imágenes, specs y FAQ viven en hojas hijas; la API los ensambla.
 */
export const productsSchema: ResourceSchema = {
  id: 'products',
  label: 'Producto',
  labelPlural: 'Productos',
  kind: 'collection',
  endpoint: {
    list: '/admin/products',
    get: '/admin/products/{key}',
    create: '/admin/products',
    update: '/admin/products/{key}',
    remove: '/admin/products/{key}',
  },
  keyField: 'slug',
  titleField: 'name',
  search: ['name', 'sku'],
  filters: [
    {
      key: 'availability',
      label: 'Disponibilidad',
      type: 'select',
      options: [
        { value: 'InStock', label: 'En stock' },
        { value: 'PreOrder', label: 'Preventa' },
        { value: 'OutOfStock', label: 'Agotado' },
      ],
    },
    { key: 'active', label: 'Activo', type: 'boolean' },
  ],
  listColumns: [
    { key: 'images', label: 'Imagen', format: 'thumbnail' },
    { key: 'name', label: 'Nombre' },
    { key: 'category_slug', label: 'Categoría' },
    { key: 'price', label: 'Precio', format: 'currency' },
    { key: 'availability', label: 'Disponibilidad' },
    { key: 'registro_sanitario', label: 'Sanitario', format: 'badge' },
    { key: 'active', label: 'Activo', format: 'boolean' },
  ],
  layout: {
    mode: 'tabs',
    sections: [
      { id: 'general', label: 'General' },
      { id: 'contenido', label: 'Contenido' },
      { id: 'imagenes', label: 'Imágenes' },
      { id: 'sanitario', label: 'Sanitario' },
      { id: 'ficha', label: 'Ficha técnica' },
      { id: 'faq', label: 'FAQ' },
    ],
  },
  fields: [
    // ── General ──
    {
      type: 'text',
      key: 'name',
      label: 'Nombre',
      required: true,
      section: 'general',
      width: 6,
    },
    {
      type: 'slug',
      key: 'slug',
      label: 'Slug',
      from: 'name',
      lockAfterCreate: true,
      required: true,
      help: 'Inmutable tras publicar.',
      section: 'general',
      width: 6,
    },
    {
      type: 'relation',
      key: 'category_slug',
      label: 'Categoría',
      required: true,
      resource: 'categories',
      valueField: 'slug',
      labelField: 'name',
      onlyActive: true,
      section: 'general',
      width: 6,
    },
    {
      type: 'text',
      key: 'sku',
      label: 'SKU',
      required: true,
      validators: { unique: true },
      section: 'general',
      width: 6,
    },
    {
      type: 'text',
      key: 'brand',
      label: 'Marca',
      section: 'general',
      width: 6,
    },
    {
      type: 'currency',
      key: 'price',
      label: 'Precio',
      required: true,
      section: 'general',
      width: 6,
    },
    {
      type: 'select',
      key: 'availability',
      label: 'Disponibilidad',
      required: true,
      options: [
        { value: 'InStock', label: 'En stock' },
        { value: 'PreOrder', label: 'Preventa' },
        { value: 'OutOfStock', label: 'Agotado' },
      ],
      section: 'general',
      width: 6,
    },
    {
      type: 'boolean',
      key: 'featured',
      label: 'Destacado',
      default: false,
      trueLabel: 'Sí',
      falseLabel: 'No',
      section: 'general',
      width: 6,
    },
    {
      type: 'boolean',
      key: 'active',
      label: 'Activo',
      default: true,
      trueLabel: 'Activo',
      falseLabel: 'Inactivo',
      section: 'general',
      width: 6,
    },
    // ── Contenido ──
    {
      type: 'textarea',
      key: 'description',
      label: 'Descripción',
      required: true,
      rows: 8,
      validators: { minWords: 150, maxWords: 300 },
      section: 'contenido',
      width: 12,
    },
    {
      type: 'text',
      key: 'seo_title',
      label: 'Título SEO',
      section: 'contenido',
      width: 12,
    },
    {
      type: 'textarea',
      key: 'seo_description',
      label: 'Descripción SEO',
      required: true,
      rows: 3,
      section: 'contenido',
      width: 12,
    },
    // ── Imágenes (mín 1; la primera es la principal) ──
    {
      type: 'list',
      key: 'images',
      label: 'Imágenes',
      required: true,
      min: 1,
      primaryFirst: true,
      positionField: 'position',
      addLabel: 'Agregar imagen',
      emptyText: 'Sin imágenes. La primera será la imagen principal.',
      itemDisplay: 'card',
      itemTitle: 'image_alt',
      itemFields: [
        { type: 'image', key: 'image_url', label: 'Imagen', required: true },
        { type: 'text', key: 'image_alt', label: 'Texto alternativo', required: true },
      ],
      section: 'imagenes',
      width: 12,
    },
    // ── Sanitario ──
    {
      type: 'text',
      key: 'registro_sanitario',
      label: 'Registro sanitario',
      help: 'Sin esto el producto no se publica.',
      section: 'sanitario',
      width: 4,
    },
    {
      type: 'select',
      key: 'clase_riesgo',
      label: 'Clase de riesgo',
      options: [
        { value: 'I', label: 'I' },
        { value: 'IIa', label: 'IIa' },
        { value: 'IIb', label: 'IIb' },
        { value: 'III', label: 'III' },
      ],
      section: 'sanitario',
      width: 4,
    },
    {
      type: 'text',
      key: 'titular_registro',
      label: 'Titular del registro',
      section: 'sanitario',
      width: 4,
    },
    // ── Ficha técnica ──
    {
      type: 'key-value',
      key: 'specs',
      label: 'Especificaciones',
      positionField: 'position',
      addLabel: 'Agregar especificación',
      emptyText: 'Sin especificaciones.',
      section: 'ficha',
      width: 12,
    },
    // ── FAQ ──
    {
      type: 'list',
      key: 'faq',
      label: 'Preguntas frecuentes',
      positionField: 'position',
      addLabel: 'Agregar pregunta',
      emptyText: 'Sin preguntas frecuentes.',
      itemDisplay: 'card',
      itemTitle: 'question',
      itemFields: [
        { type: 'text', key: 'question', label: 'Pregunta', required: true },
        { type: 'textarea', key: 'answer', label: 'Respuesta', required: true, rows: 4 },
      ],
      section: 'faq',
      width: 12,
    },
  ],
};
